on:
  label:
    types:
      - created
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CMake config
        run: |
            cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .
      - name: Build/Install Snowball
        run: |
            sudo make install
      - name: Runing Bench (fib)
        run: |
            cd bench/fib
            chmod +x ./run.sh
            ./run.sh

